title: MABS 2023 - The 24th International Workshop on Multi-Agent-Based Simulation
email: mabs2023@easychair.org
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "mabs2023/" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: MABS2023
  email: "mabs2023@easychair.org"

header_pages:
  - committees.md
  - call_for_papers.md
  - accepted_papers.md
  - registration.md
  - invited.md
  - program.md
  - postproceedings.md
  - mabs_series.md
  
# Build settings
theme: minima
